### ISSUE TITLE
Screen Share / Live Streaming

### ISSUE THREAD

**Issue by asharma-gh** [revoltchat/vortex#9] opened 2021-11-16 00:42 UTC
One of the features which makes discord particularly useful is live-streaming, specifically sharing screens for low-latency high resolution streams.

**Comment by Rexogamer** [comment] 2022-01-01 00:19
Duplicate of #4.

**Closed as not planned by Rexogamer** 2022-01-01 00:19 UTC
Labels: duplicate, enhancement

**Comment by insertish** [comment] 2022-01-02 12:29
(GH only allows people with write access to set duplicates)
Duplicate of #4

edit: it still wont work i give up
